### PR TITLE
feat: add tagline for movies

### LINKED ISSUE #451: [feature request] add taglines for films.
Almost all films have taglines (as seen here in the matadata and in the jellyfin app)
Screenshot_20230728-184709
Screenshot_20230728-184721
But it's not showing in findroid?
Screenshot_20230728-184728
Is it a possibility?

### PR DESCRIPTION
**Pull request by Natanel-Shitrit**
## Feature Preview
screen

## Related Issues
- Resolves #451

### CODE REVIEW

**Comment by jarnedemeulemeester** [comment]
I am not the biggest fan of a tagline (especially on a space constrained mobile screen) but if we do decide to add it I would put it underneath the buttons I think

**Comment by Natanel-Shitrit** [comment]
> I am not the biggest fan of a tagline (especially on a space constrained mobile screen) but if we do decide to add it I would put it underneath the buttons I think.
> 
> @Natanel-Shitrit could you try that and see if it looks good?

Sure, I'll move it later today and test :)

**Comment by Natanel-Shitrit** [comment]
> I am not the biggest fan of a tagline (especially on a space constrained mobile screen) but if we do decide to add it I would put it underneath the buttons I think.
> 
> @Natanel-Shitrit could you try that and see if it looks good?



Looks good

**Comment by Natanel-Shitrit** [comment]
Looks good

I would actually make the text bigger, what do you think?

**Comment by Natanel-Shitrit** [comment]
Looks like this now.
screen

**Comment by Natanel-Shitrit** [comment]
What do you think about moving it to the page app bar? (top bar where you have the name of the movie)
It's currently just a duplicating the movie name so it could be nice 😄

**Comment by Natanel-Shitrit** [comment]
I guess we can close this after deciding it's not really necessary.
Up to you @jarnedemeulemeester 😄

**Pull request closed without merging**
