### PR TITLE
fix: pip zoom start player maximized

### PR DESCRIPTION
**Pull request by cd16b**
Sorry, I found one more problem.

### CODE REVIEW

**Comment by Natanel-Shitrit** [comment]
Why aren't you just tracking `isZoomEnabled` inside `updateZoomMode` instead of updating it in each place you call `updateZoomMode`?

**Comment by Natanel-Shitrit** [comment]
`isZoomEnabled` is not used anywhere, it can be discarded entirely.

**Comment by cd16b** [comment]
> Why aren't you just tracking `isZoomEnabled` inside `updateZoomMode` instead of updating it in each place you call `updateZoomMode`?

You are right. To avoid future issues, I will update `isZoomEnabled` inside `updateZoomMode`.

**Comment by Natanel-Shitrit** [comment]
> `isZoomEnabled` is not used anywhere, it can be discarded entirely.

Please note that it can be just discarded because this value is not being used anywhere.

**Comment by cd16b** [comment]
> `isZoomEnabled` is not used anywhere, it can be discarded entirely.

It's used in line 332: `isZoomEnabled = scaleFactor > 1` to call `updateZoomMode`.
I removed the 'private' modifier so I could use it when exiting pip mode in the PlayerActivity.

**Comment by Natanel-Shitrit** [comment]
> > `isZoomEnabled` is not used anywhere, it can be discarded entirely.
> 
> It's used in line 332: `isZoomEnabled = scaleFactor > 1` to call `updateZoomMode`. I removed the 'private' modifier so I could use it when exiting pip mode in the PlayerActivity.

it's not used, it's being assigned a value, you can just pass `scaleFactor > 1` to the function or create a local `val` if you want a variable for readability.

**Comment by cd16b** [comment]
> > > `isZoomEnabled` is not used anywhere, it can be discarded entirely.
> > 
> > 
> > It's used in line 332: `isZoomEnabled = scaleFactor > 1` to call `updateZoomMode`. I removed the 'private' modifier so I could use it when exiting pip mode in the PlayerActivity.
> 
> it's not used, it's being assigned a value, you can just pass `scaleFactor > 1` to the function or create a local `val` if you want a variable for readability.

Ok, but before entering picture-in-picture mode, I need to save the zoom state. This is because when using the MPV player, I cannot use playerView.getGlobalVisibleRect() and it behaves strangely when the video is zoomed.

**Comment by cd16b** [comment]
> > Why aren't you just tracking `isZoomEnabled` inside `updateZoomMode` instead of updating it in each place you call `updateZoomMode`?
> 
> You are right. To avoid future issues, I will update `isZoomEnabled` inside `updateZoomMode`.

I'm reverting the latest commit cause I have to save the zoom state before changing it.

**Comment by cd16b** [comment]
Now tracking `isZoomEnabled` inside `updateZoomMode`

**Pull request merged**
