### PR TITLE
feat: android tv

### LINKED ISSUE #23: FEATURE REQUEST Android TV
Hi please could you make this client for Android TV I love how fast this client is, it's unbeatable 

So again Please for Android TV

### LINKED ISSUE #534: Feature Request: Simplified track selection menu for mpv
Mpv player shows the tracks in a very not user friendly way (language codes rather then names). I know you don't develope the players used but is it possible to use a more friendly design for the menus in mpv?
Screenshot_20230828-231754
Exo👆
Screenshot_20230828-231731
Mpv👆
Ideally it would be language, and if the track had a name then the name as well (for stuff like commentery tracks)

### PR DESCRIPTION
**Pull request by jarnedemeulemeester**
It's finally time to merge the Android TV code back to the main branch.
There are still some things that need to be implemented. But these will come in smaller separate PRs.

Here is a quick overview of all the features currently implemented:
## Home
The home screen displays the "Continue Watching", "Next Up" and latest items of each library with progress indicators.
At the top are three tabs. Of these three only search has not been implemented yet.
Settings are accessed using the profile button at the top right.

home

- [x] Continue Watching
- [x] Next Up
- [x] Latest <library>

## Libraries
Shows a list of all the libraries the user has access to. Currently does not implement a way to sort or filter.

libraries

- [x] List of libraries
- [ ] Sort / filter

## Library
Displays a list of movies or shows with watched indicators. Does not have a way to sort or filter yet.

library

- [x] List of movies / shows
- [ ] Sort / filter

## Movie
Displays all the expected information except for metadata chips and cast & crew. 
You can play the movie, watch the trailer, mark as played or add to favorites.

movie

- [x] Title
- [x] Original title
- [ ] Metadata chips
- [x] Production year
- [x] Runtime
- [x] Official rating
- [x] Community rating
- [x] Overview
- [x] Play
- [x] Watch trailer
- [x] Mark as watched / favorite
- [x] Genres
- [x] Director
- [x] Writers
- [ ] Cast & Crew

## Show
Same as the movie screen but also lists the seasons.

show

- [x] Same as movie
- [x] Seasons

## Season
Lists all episodes in the season with progress indicators and watched status. 
Does not have the ability to sort or filter yet. 
I will probably also add a feature to automatically scroll to the next up episode.

season

- [x] Title
- [x] Show name
- [x] List of episodes
- [ ] Sort / filter

## Player
Play and pause the media, change audio or subtitle tracks and seeking are all implemented. 
There is currently no way to completely disable the audio or subtitles. 
Skip intro and trickplay will also be added later.

player

- [x] Play / pause
- [x] Change audio track
- [x] Change subtitle track
- [x] Seek
- [ ] Skip intro
- [ ] Trickplay

## Settings
Currently there are only a few settings available.
- Change the preferred language of the audio and subtitle tracks. 
- Use mpv as the player.
- Switch user and or server.
- Enable or disable the image cache.

settings

- [x] Language
- [ ] Appearance
- [x] Player
- [x] Users
- [x] Servers
- [ ] Device
- [ ] Network
- [x] Cache
- [ ] About

## Servers
Lists all configured servers. 
Discovered server are shown in the same list.
Add a server by manually typing in the server address.

servers
addserver

- [x] List of servers
  - [ ] Display the server address
- [x] Server discovery
- [x] Add server
- [ ] Delete server

## Users
Lists all configured and public users.
Log in using username / password or via Quick Connect (not shown in screenshot because the demo server does not have Quick Connect enabled).

users
login

- [x] List of users
- [x] Add user / login
- [ ] Delete user

Closes #23 
Closes #534

### CODE REVIEW

**Comment by drizzt09** [comment]
this looks beautiful.
What is timeline of apk release?

**Comment by jothi-prasath** [comment]
🎉🎉

**Comment by Betalos** [comment]
@drizzt09 I guess it still far away, I tried the debug build in chromecast with Google tv, the playback is not working, also some minor navigation issues.
So I guess it still need some ironing before release.

**Comment by EnduringGuerila** [comment]
I compiled and installed tv-libre-armeabi-v7a-debug.apk on our Sony Bravia running android 10. 
I'd love to provide feedback somewhere if it'll help development.

**Comment by ayykamp** [comment]
The TV UI looks really good :) Only thing is that the posters should maybe be displayed when viewing a single movie/show and not just the background image.

**Comment by zivshek** [comment]
great work!

**Pull request merged**
