### PR TITLE
refactor: remove `cleanUpOldDownloads`

### PR DESCRIPTION
**Pull request by Natanel-Shitrit**
Pretty sure enough time has passed since this was introduced and we can remove it :)

### CODE REVIEW

**Review by jarnedemeulemeester — CHANGES_REQUESTED** [review]
I agree, we should remove it now. There are only a handfull of people still on an older version before the downloads rework. And those people probably cannot update because their device is running an old Android version.

I think we should also delete the `appPreference` `downloadsMigrated` variable :smile: 
https://github.com/jarnedemeulemeester/findroid/blob/d65591a19ec3beefc7daaf63ec6811777a41d8d7/preferences/src/main/java/dev/jdtech/jellyfin/AppPreferences.kt#L148C1-L153

**Comment by Natanel-Shitrit** [comment]
> I agree, we should remove it now. There are only a handfull of people still on an older version before the downloads rework. And those people probably cannot update because their device is running an old Android version.
> 
> I think we should also delete the `appPreference` `downloadsMigrated` variable :smile: 
> https://github.com/jarnedemeulemeester/findroid/blob/d65591a19ec3beefc7daaf63ec6811777a41d8d7/preferences/src/main/java/dev/jdtech/jellyfin/AppPreferences.kt#L148C1-L153

Oops, I totally forgot abot that, thanks - I'll add it once I'm home!

**Review by jarnedemeulemeester — APPROVED** [review]
I rebased the PR onto main and removed the `downloadsMigrated` prefrence since it was a small change I could easily commit

**Comment by Natanel-Shitrit** [comment]
> I rebased the PR onto main and removed the `downloadsMigrated` prefrence since it was a small change I could easily commit

Thank you 🙏
I'm sorry I wasn't able to complete this PR.

Hard times - hope to return supporting Findroid soon ♥️

**Comment by jarnedemeulemeester** [comment]
> Thank you 🙏 I'm sorry I wasn't able to complete this PR.
> 
> Hard times - hope to return supporting Findroid soon ♥️

No problem man! I haven't been able to do much myself either. 

Take care ♥️

**Pull request merged**
