### PR TITLE
Support collections

### LINKED ISSUE #18: Collections
No content, such as movies or shows, is displayed in collections, they are just empty.

Android: 11 (OneUi 3.1)

### PR DESCRIPTION
**Pull request by lsrom**
Collections are now displayed under My Media tab and correctly show movies and/shows inside them.

Closes #18

### CODE REVIEW

**Comment by jarnedemeulemeester** [comment]
This indeed shows the collections and works. But is the user adds episodes to the collection they are displayed as movies/series and navigate to the MediaInfoFragment. Maybe we should use the same layout as the favorites fragment to display the contents of a collection?

**Comment by lsrom** [comment]
I see. I don't have any favorites or episodes in the collections so I didn't notice. I'll make new fragment for this then.

**Comment by jarnedemeulemeester** [comment]
I think you should be able to reuse the fragment_favorite.xml layout file.
Actually the code is also almost the same, just a different request in the viewmodel to the repository I think.

It's okay if you just copy the code and change it where needed

**Comment by JulioNahum** [comment]
We all thank you for the great effort you put into this wonderful app, but please, when will the next update be released?

**Comment by BluePixel4k** [comment]
Is there any update for this PR?
I would love to see this feature in the app. 😇

**Comment by jarnedemeulemeester** [comment]
Superseded by #252

**Pull request closed without merging**
